### ISSUE TITLE
Websocket flv settings

### ISSUE THREAD

**Issue by myhu** [Bilibili/flv.js#96] opened 2017-02-10 17:04 UTC
Hi,

When I'm trying to use this setting I've got an error:
{
    // FLV over WebSocket
    "type": "flv",
    "isLive": true,
    "url": "ws://127.0.0.1:9090/live/livestream.flv"
}
Fetch API cannot load ws://127.0.0.1:9090/. URL scheme must be "http" or "https" for CORS request.

If I'm using http protocol, everything is working fine...only websocket is not working in Chrome

On the server side of course I set the proper CORS settings...

What gonna be what I forget to set, or ?

thx in advance,
misi
![flv js ws error chrome](https://cloud.githubusercontent.com/assets/7011020/22836055/4bf5f652-efbb-11e6-9f50-a7eb5d7baee5.jpg)

**Comment by xqq** [comment] 2017-02-11 12:32
websocket url should be handled by WebSocketLoader. This works well in the master code.
Did you modify any part of IOController ?

**Comment by myhu** [comment] 2017-02-12 17:44
I did not changed anything, only build a new flv.js...I've tried again just in case, but the sam error came across...


"I do not understand, my response is not seeing, what i've already reported yesterday...So maybe right now, I'm gonna be luckier...argh"

**Comment by myhu** [comment] 2017-02-13 10:15
In the meantime I've checked what you mentioned IOController.js file.
It looks "this._isWebSocketURL = /wss?:\/\/(.+?)\//.test(dataSource.url);" this part is not working
When I miss out this part and forced _selectLoader() to use WebsocketLoader, every errors in a question are eliminated...

**Comment by xqq** [comment] 2017-02-13 14:39
It should be caused by the incorrect regexp
fixed in https://github.com/Bilibili/flv.js/commit/537f7e8e89605c7762c5fcf97a8d65252e1dc6c6

**Closed** 2017-02-15 14:31 UTC

**Comment by zgy520** [comment] 2017-02-25 08:20
@myhu hello, can you share you demo. i now do it, but can not implement it

**Comment by hj009** [comment] 2017-03-24 02:35
@myhu你好，你可以分享你演示吗 我现在做，但不能实现它+1
